-- BUG-543: Rollback — re-insert both deleted rows
--
-- Before running the migration, capture the rows that will be deleted:
--
--   \copy (
--     SELECT id, order_id, product_id, category_id, tx_type, amount, note, created_by, created_at
--     FROM finance_transactions ft
--     INNER JOIN orders o ON o.id = ft.order_id
--     WHERE o.order_number = 'ORD-26042674'
--       AND ft.tx_type = 'rental_revenue'
--       AND (
--         (ft.amount < 0 AND ft.note LIKE 'BUG-517%')
--         OR ft.id = (
--           SELECT ft2.id FROM finance_transactions ft2
--           INNER JOIN orders o2 ON o2.id = ft2.order_id
--           WHERE o2.order_number = 'ORD-26042674'
--             AND ft2.tx_type = 'rental_revenue' AND ft2.amount > 0
--           ORDER BY ft2.created_at ASC LIMIT 1
--         )
--       )
--   ) TO '/tmp/deleted_ft_ord_26042674.csv' WITH CSV HEADER;
--
-- To rollback, restore from the CSV:
--
--   \copy finance_transactions (id, order_id, product_id, category_id, tx_type, amount, note, created_by, created_at)
--   FROM '/tmp/deleted_ft_ord_26042674.csv' WITH CSV HEADER;
--
-- Or insert manually using the exact IDs from the dry-run output:
--
-- BEGIN;
-- INSERT INTO finance_transactions (id, order_id, tx_type, amount, note, created_at)
-- VALUES
--   -- Row 1: original duplicate +590
--   ('0cf9e80e-3180-47fa-aa2e-ab276dd99f8c', '<order-uuid>', 'rental_revenue', 590, 'Rental revenue', '<timestamp>'),
--   -- Row 2: BUG-517 reconciliation reversal -590
--   ('ba1f0251-026a-403c-b009-73051ca6946a', '<order-uuid>', 'rental_revenue', -590, 'BUG-517 reconciliation: remove duplicate revenue record', '<timestamp>');
-- COMMIT;
--
-- Replace <order-uuid> and <timestamp> with actual values from dry-run output.
